inputs:
  python-version:
    type: string
runs:
  using: composite
  steps:
    # Install toolchain.
    - run: pipx install poetry
      shell: bash
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version || '3.12' }}
        cache: poetry
    # Run pre-install checks.
    - run: poetry check
      shell: bash
    - run: poetry check --lock
      shell: bash
