version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
    - pip install poetry
    - poetry config virtualenvs.create false
    post_install:
    - poetry install --only docs

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
