version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.13"
  jobs:
    # See: https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-poetry
    post_create_environment:
    - pip install poetry
    post_install:
    - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --all-extras

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
