name: Build

on: push

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
      fail-fast: false
    env:
      PYTHONDEVMODE: 1
    steps:
    - uses: actions/checkout@v4
    # Install toolchain.
    - run: pipx install poetry
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: poetry
    # Install dependencies.
    - run: poetry check
    - run: poetry check --lock
    - run: poetry run python --version
    - run: poetry install
    # Run checks.
    - run: poetry run ruff check
    - run: poetry run ruff format --check
    - run: poetry run mypy
    # Run tests.
    - run: poetry run coverage run --data-file=".coverage-${{ matrix.python-version }}" -m pytest
    # Upload coverage.
    - uses: actions/upload-artifact@v4
      with:
        name: coverage-${{ matrix.python-version }}
        path: .coverage-${{ matrix.python-version }}

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # Install toolchain.
    - run: pipx install poetry
    - uses: actions/setup-python@v5
      with:
        python-version: "3.x"
        cache: poetry
    # Install dependencies.
    - run: poetry install --without dev --with docs
    # Build docs.
    - run: poetry run sphinx-build -W docs docs/_build

  report:
    runs-on: ubuntu-latest
    needs:
    - test
    - docs
    if: always()
    steps:
    - uses: actions/checkout@v4
    # Fail if any needed jobs fail.
    # This, along with `if: always()`, allows this job to act as the single required status check for the workflow.
    - run: exit 1
      if: needs.test.result != 'success' || needs.docs.result != 'success'
    # Download coverage.
    - uses: actions/download-artifact@v4
      with:
        pattern: coverage-*
        merge-multiple: true
    - run: ls -a
    # Install toolchain.
    - run: pipx install poetry
    - uses: actions/setup-python@v5
      with:
        python-version: "3.x"
        cache: poetry
    # Install dependencies.
    - run: poetry install
    # Report coverage.
    - run: poetry run coverage combine
    - run: poetry run coverage report
